###############################################################
#     Welcome to COON & friends secret communication shell    #
#                                                             #
#       All connections are monitored and recorded            #
#            and can be used against you for the              #
#		  sake of the United-States                   #
#                                                             #
#   Disconnect IMMEDIATELY if you are not an authorized user! #           
###############################################################
# FLAG #1
# {Sc**w you guys, I'm going home !}
# Token #1 : Ag (You should save this token somewhere)
